# Generated by Django 2.1.3 on 2018-11-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100, verbose_name='title')),
                ('song_author', models.CharField(max_length=100, verbose_name='author')),
                ('song_length', models.IntegerField(default=0, verbose_name='duration')),
                ('song_url', models.URLField(unique=True, verbose_name='url')),
            ],
        ),
    ]
