# Generated by Django 2.1.2 on 2018-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='artist',
            field=models.CharField(max_length=100, null=True, verbose_name='가수명'),
        ),
    ]
