# Generated by Django 2.1.2 on 2018-11-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auction_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='cover_location',
            field=models.FilePathField(null=True, path='/static/image'),
        ),
    ]
