# Generated by Django 2.1.2 on 2018-11-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_cover_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='cover_location',
        ),
    ]
