# Generated by Django 2.1.2 on 2018-11-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_remove_auction_cover_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='cover_path',
            field=models.CharField(max_length=200, null=True, verbose_name='파일경로'),
        ),
    ]
