# Generated by Django 2.1.2 on 2018-11-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auction_cover_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='url',
            field=models.URLField(null=True, unique=True, verbose_name='url'),
        ),
    ]
