# Generated by Django 2.1.2 on 2018-11-06 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auction_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='url',
        ),
    ]
