# Generated by Django 2.1.2 on 2018-11-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_remove_auction_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='video_path',
            field=models.CharField(max_length=100, null=True, verbose_name='비디오경로'),
        ),
    ]
